### ISSUE TITLE
rails_tracker as Kanban board

### ISSUE THREAD

**Issue by kirantpatil** [originated/rails_tracker#7]
Hi,

How about making it as simple Kanban board?

Ex: https://github.com/rauhryan/huboard

**Comment by originated** [comment]
A Kanban style would be nice but not sure if it be hugely beneficial.  The front facing UI is meant for your end users to track a particular ticket and currently there would only be 1 spot drag/drop the ticket.  Rails Tracker is trying to solve the consumer facing side -- Huboard is great for the developers.

**Comment by kirantpatil** [comment]
Thanks.
